const vocabulary = [
  { id: "v1", arabic: "كتاب", german: "Buch", article: "das", plural: "Bücher", example_de: "Ich lese ein Buch.", example_ar: "أنا أقرأ كتابًا.", level: "A1", category: "Alltag" },
  { id: "v2", arabic: "قلم", german: "Stift", article: "der", plural: "Stifte", example_de: "Der Stift ist blau.", example_ar: "القلم أزرق.", level: "A1", category: "Alltag" },
  { id: "v3", arabic: "حقيبة", german: "Tasche", article: "die", plural: "Taschen", example_de: "Meine Tasche ist groß.", example_ar: "حقيبتي كبيرة.", level: "A1", category: "Alltag" },
  { id: "v4", arabic: "شارع", german: "Straße", article: "die", plural: "Straßen", example_de: "Die Straße ist ruhig.", example_ar: "الشارع هادئ.", level: "A1", category: "Alltag" },
  { id: "v5", arabic: "مدينة", german: "Stadt", article: "die", plural: "Städte", example_de: "Die Stadt ist schön.", example_ar: "المدينة جميلة.", level: "A1", category: "Alltag" },
  { id: "v6", arabic: "هاتف", german: "Handy", article: "das", plural: "Handys", example_de: "Mein Handy ist neu.", example_ar: "هاتفي جديد.", level: "A1", category: "Alltag" },
  { id: "v7", arabic: "ساعة", german: "Uhr", article: "die", plural: "Uhren", example_de: "Die Uhr ist teuer.", example_ar: "الساعة غالية.", level: "A1", category: "Alltag" },
  { id: "v8", arabic: "صديق", german: "Freund", article: "der", plural: "Freunde", example_de: "Mein Freund kommt heute.", example_ar: "صديقي يأتي اليوم.", level: "A1", category: "Alltag" },
  { id: "v9", arabic: "عائلة", german: "Familie", article: "die", plural: "Familien", example_de: "Meine Familie ist hier.", example_ar: "عائلتي هنا.", level: "A1", category: "Alltag" },
  { id: "v10", arabic: "محطة", german: "Bahnhof", article: "der", plural: "Bahnhöfe", example_de: "Der Bahnhof ist weit.", example_ar: "محطة القطار بعيدة.", level: "A2", category: "Alltag" },
  { id: "v11", arabic: "موعد", german: "Termin", article: "der", plural: "Termine", example_de: "Ich habe einen Termin.", example_ar: "لدي موعد.", level: "A2", category: "Alltag" },
  { id: "v12", arabic: "مفتاح", german: "Schlüssel", article: "der", plural: "Schlüssel", example_de: "Der Schlüssel ist im Haus.", example_ar: "المفتاح في البيت.", level: "A1", category: "Alltag" },
  { id: "v13", arabic: "خبز", german: "Brot", article: "das", plural: "Brote", example_de: "Ich kaufe frisches Brot.", example_ar: "أشتري خبزًا طازجًا.", level: "A1", category: "Essen" },
  { id: "v14", arabic: "تفاحة", german: "Apfel", article: "der", plural: "Äpfel", example_de: "Der Apfel ist süß.", example_ar: "التفاحة حلوة.", level: "A1", category: "Essen" },
  { id: "v15", arabic: "ماء", german: "Wasser", article: "das", plural: "-", example_de: "Ich trinke Wasser.", example_ar: "أشرب ماء.", level: "A1", category: "Essen" },
  { id: "v16", arabic: "شاي", german: "Tee", article: "der", plural: "Tees", example_de: "Möchtest du Tee?", example_ar: "هل تريد شايًا؟", level: "A1", category: "Essen" },
  { id: "v17", arabic: "قهوة", german: "Kaffee", article: "der", plural: "Kaffees", example_de: "Ich bestelle einen Kaffee.", example_ar: "أطلب قهوة.", level: "A1", category: "Essen" },
  { id: "v18", arabic: "جبن", german: "Käse", article: "der", plural: "Käse", example_de: "Der Käse ist lecker.", example_ar: "الجبن لذيذ.", level: "A1", category: "Essen" },
  { id: "v19", arabic: "وجبة", german: "Mahlzeit", article: "die", plural: "Mahlzeiten", example_de: "Das ist eine warme Mahlzeit.", example_ar: "هذه وجبة ساخنة.", level: "A2", category: "Essen" },
  { id: "v20", arabic: "خضار", german: "Gemüse", article: "das", plural: "Gemüse", example_de: "Wir kaufen frisches Gemüse.", example_ar: "نشتري خضارًا طازجًا.", level: "A1", category: "Essen" },
  { id: "v21", arabic: "فاكهة", german: "Obst", article: "das", plural: "Obst", example_de: "Ich esse gern Obst.", example_ar: "أحب أكل الفاكهة.", level: "A1", category: "Essen" },
  { id: "v22", arabic: "مطعم", german: "Restaurant", article: "das", plural: "Restaurants", example_de: "Das Restaurant ist voll.", example_ar: "المطعم ممتلئ.", level: "A2", category: "Essen" },
  { id: "v23", arabic: "حساء", german: "Suppe", article: "die", plural: "Suppen", example_de: "Die Suppe ist heiß.", example_ar: "الحساء ساخن.", level: "A1", category: "Essen" },
  { id: "v24", arabic: "سكر", german: "Zucker", article: "der", plural: "Zucker", example_de: "Bitte ohne Zucker.", example_ar: "من فضلك بدون سكر.", level: "A2", category: "Essen" },
  { id: "v25", arabic: "عمل", german: "Arbeit", article: "die", plural: "Arbeiten", example_de: "Ich fahre zur Arbeit.", example_ar: "أذهب إلى العمل.", level: "A1", category: "Arbeit" },
  { id: "v26", arabic: "مكتب", german: "Büro", article: "das", plural: "Büros", example_de: "Das Büro ist modern.", example_ar: "المكتب حديث.", level: "A1", category: "Arbeit" },
  { id: "v27", arabic: "زميل", german: "Kollege", article: "der", plural: "Kollegen", example_de: "Mein Kollege hilft mir.", example_ar: "زميلي يساعدني.", level: "A2", category: "Arbeit" },
  { id: "v28", arabic: "مدير", german: "Chef", article: "der", plural: "Chefs", example_de: "Der Chef ist freundlich.", example_ar: "المدير ودود.", level: "A2", category: "Arbeit" },
  { id: "v29", arabic: "اجتماع", german: "Meeting", article: "das", plural: "Meetings", example_de: "Wir haben ein Meeting.", example_ar: "لدينا اجتماع.", level: "A2", category: "Arbeit" },
  { id: "v30", arabic: "مشروع", german: "Projekt", article: "das", plural: "Projekte", example_de: "Das Projekt ist wichtig.", example_ar: "المشروع مهم.", level: "A2", category: "Arbeit" },
  { id: "v31", arabic: "موعد نهائي", german: "Deadline", article: "die", plural: "Deadlines", example_de: "Die Deadline ist morgen.", example_ar: "الموعد النهائي غدًا.", level: "A2", category: "Arbeit" },
  { id: "v32", arabic: "حاسوب", german: "Computer", article: "der", plural: "Computer", example_de: "Mein Computer ist schnell.", example_ar: "حاسوبي سريع.", level: "A1", category: "Arbeit" },
  { id: "v33", arabic: "بريد إلكتروني", german: "E-Mail", article: "die", plural: "E-Mails", example_de: "Ich schreibe eine E-Mail.", example_ar: "أكتب بريدًا إلكترونيًا.", level: "A1", category: "Arbeit" },
  { id: "v34", arabic: "استراحة", german: "Pause", article: "die", plural: "Pausen", example_de: "Wir machen eine Pause.", example_ar: "نأخذ استراحة.", level: "A1", category: "Arbeit" },
  { id: "v35", arabic: "راتب", german: "Gehalt", article: "das", plural: "Gehälter", example_de: "Das Gehalt ist gut.", example_ar: "الراتب جيد.", level: "A2", category: "Arbeit" },
  { id: "v36", arabic: "وظيفة", german: "Job", article: "der", plural: "Jobs", example_de: "Ich suche einen Job.", example_ar: "أبحث عن وظيفة.", level: "A1", category: "Arbeit" },
  { id: "v37", arabic: "طبيب", german: "Arzt", article: "der", plural: "Ärzte", example_de: "Der Arzt ist im Zimmer.", example_ar: "الطبيب في الغرفة.", level: "A1", category: "Arzt" },
  { id: "v38", arabic: "مستشفى", german: "Krankenhaus", article: "das", plural: "Krankenhäuser", example_de: "Das Krankenhaus ist groß.", example_ar: "المستشفى كبير.", level: "A2", category: "Arzt" },
  { id: "v39", arabic: "دواء", german: "Medikament", article: "das", plural: "Medikamente", example_de: "Ich nehme ein Medikament.", example_ar: "أخذ دواء.", level: "A2", category: "Arzt" },
  { id: "v40", arabic: "ألم", german: "Schmerz", article: "der", plural: "Schmerzen", example_de: "Ich habe Schmerzen.", example_ar: "لدي ألم.", level: "A1", category: "Arzt" },
  { id: "v41", arabic: "حمّى", german: "Fieber", article: "das", plural: "Fieber", example_de: "Er hat Fieber.", example_ar: "لديه حمى.", level: "A1", category: "Arzt" },
  { id: "v42", arabic: "موعد طبي", german: "Arzttermin", article: "der", plural: "Arzttermine", example_de: "Ich brauche einen Arzttermin.", example_ar: "أحتاج موعدًا طبيًا.", level: "A2", category: "Arzt" },
  { id: "v43", arabic: "علاج", german: "Behandlung", article: "die", plural: "Behandlungen", example_de: "Die Behandlung hilft.", example_ar: "العلاج مفيد.", level: "A2", category: "Arzt" },
  { id: "v44", arabic: "دوار", german: "Schwindel", article: "der", plural: "Schwindel", example_de: "Mir ist schwindelig.", example_ar: "أشعر بالدوار.", level: "A2", category: "Arzt" },
  { id: "v45", arabic: "صداع", german: "Kopfschmerz", article: "der", plural: "Kopfschmerzen", example_de: "Ich habe Kopfschmerzen.", example_ar: "لدي صداع.", level: "A1", category: "Arzt" },
  { id: "v46", arabic: "وصفة", german: "Rezept", article: "das", plural: "Rezepte", example_de: "Der Arzt schreibt ein Rezept.", example_ar: "الطبيب يكتب وصفة.", level: "A2", category: "Arzt" },
  { id: "v47", arabic: "فحص", german: "Untersuchung", article: "die", plural: "Untersuchungen", example_de: "Die Untersuchung dauert kurz.", example_ar: "الفحص قصير.", level: "A2", category: "Arzt" },
  { id: "v48", arabic: "صيدلية", german: "Apotheke", article: "die", plural: "Apotheken", example_de: "Die Apotheke ist um die Ecke.", example_ar: "الصيدلية على الزاوية.", level: "A1", category: "Arzt" },
  { id: "v49", arabic: "شقة", german: "Wohnung", article: "die", plural: "Wohnungen", example_de: "Die Wohnung ist hell.", example_ar: "الشقة مضيئة.", level: "A1", category: "Wohnung" },
  { id: "v50", arabic: "غرفة", german: "Zimmer", article: "das", plural: "Zimmer", example_de: "Das Zimmer ist klein.", example_ar: "الغرفة صغيرة.", level: "A1", category: "Wohnung" },
  { id: "v51", arabic: "مطبخ", german: "Küche", article: "die", plural: "Küchen", example_de: "Die Küche ist sauber.", example_ar: "المطبخ نظيف.", level: "A1", category: "Wohnung" },
  { id: "v52", arabic: "حمام", german: "Bad", article: "das", plural: "Bäder", example_de: "Das Bad ist modern.", example_ar: "الحمام حديث.", level: "A1", category: "Wohnung" },
  { id: "v53", arabic: "شرفة", german: "Balkon", article: "der", plural: "Balkone", example_de: "Der Balkon ist groß.", example_ar: "الشرفة كبيرة.", level: "A2", category: "Wohnung" },
  { id: "v54", arabic: "إيجار", german: "Miete", article: "die", plural: "Mieten", example_de: "Die Miete ist hoch.", example_ar: "الإيجار مرتفع.", level: "A2", category: "Wohnung" },
  { id: "v55", arabic: "نافذة", german: "Fenster", article: "das", plural: "Fenster", example_de: "Das Fenster ist offen.", example_ar: "النافذة مفتوحة.", level: "A1", category: "Wohnung" },
  { id: "v56", arabic: "باب", german: "Tür", article: "die", plural: "Türen", example_de: "Die Tür ist schwer.", example_ar: "الباب ثقيل.", level: "A1", category: "Wohnung" },
  { id: "v57", arabic: "أثاث", german: "Möbel", article: "die", plural: "Möbel", example_de: "Die Möbel sind neu.", example_ar: "الأثاث جديد.", level: "A2", category: "Wohnung" },
  { id: "v58", arabic: "غسالة", german: "Waschmaschine", article: "die", plural: "Waschmaschinen", example_de: "Die Waschmaschine läuft.", example_ar: "الغسالة تعمل.", level: "A2", category: "Wohnung" },
  { id: "v59", arabic: "ثلاجة", german: "Kühlschrank", article: "der", plural: "Kühlschränke", example_de: "Der Kühlschrank ist leer.", example_ar: "الثلاجة فارغة.", level: "A2", category: "Wohnung" },
  { id: "v60", arabic: "أجرة الكهرباء", german: "Stromrechnung", article: "die", plural: "Stromrechnungen", example_de: "Die Stromrechnung kommt monatlich.", example_ar: "فاتورة الكهرباء تأتي شهريًا.", level: "A2", category: "Wohnung" }
];

const sentences = [
  { id: "s1", arabic: "أنا أتعلم الألمانية كل يوم.", german: "Ich lerne jeden Tag Deutsch.", level: "A1", category: "Alltag" },
  { id: "s2", arabic: "هل يمكنك مساعدتي من فضلك؟", german: "Kannst du mir bitte helfen?", level: "A1", category: "Alltag" },
  { id: "s3", arabic: "أين محطة الحافلة؟", german: "Wo ist die Bushaltestelle?", level: "A1", category: "Alltag" },
  { id: "s4", arabic: "سأعود في الساعة السادسة.", german: "Ich komme um sechs Uhr zurück.", level: "A2", category: "Alltag" },
  { id: "s5", arabic: "أنا أبحث عن سوبرماركت قريب.", german: "Ich suche einen Supermarkt in der Nähe.", level: "A2", category: "Alltag" },
  { id: "s6", arabic: "أريد شراء خبز وخضار.", german: "Ich möchte Brot und Gemüse kaufen.", level: "A1", category: "Essen" },
  { id: "s7", arabic: "القائمة تحتوي على وجبات نباتية.", german: "Die Speisekarte hat vegetarische Gerichte.", level: "A2", category: "Essen" },
  { id: "s8", arabic: "هل يمكنني الحصول على ماء من فضلك؟", german: "Kann ich bitte Wasser bekommen?", level: "A1", category: "Essen" },
  { id: "s9", arabic: "أحب القهوة بدون سكر.", german: "Ich mag Kaffee ohne Zucker.", level: "A1", category: "Essen" },
  { id: "s10", arabic: "الفاتورة من فضلك.", german: "Die Rechnung bitte.", level: "A1", category: "Essen" },
  { id: "s11", arabic: "لدي اجتماع صباح الغد.", german: "Ich habe morgen früh ein Meeting.", level: "A2", category: "Arbeit" },
  { id: "s12", arabic: "أرسل لي البريد الإلكتروني حالاً.", german: "Schick mir die E-Mail sofort.", level: "A2", category: "Arbeit" },
  { id: "s13", arabic: "هذا المشروع مهم جدًا.", german: "Dieses Projekt ist sehr wichtig.", level: "A2", category: "Arbeit" },
  { id: "s14", arabic: "سآخذ استراحة قصيرة.", german: "Ich mache eine kurze Pause.", level: "A1", category: "Arbeit" },
  { id: "s15", arabic: "هل يمكننا تحديد موعد جديد؟", german: "Können wir einen neuen Termin vereinbaren?", level: "A2", category: "Arbeit" },
  { id: "s16", arabic: "أشعر بالحمى منذ أمس.", german: "Ich habe seit gestern Fieber.", level: "A1", category: "Arzt" },
  { id: "s17", arabic: "أحتاج إلى دواء للسعال.", german: "Ich brauche ein Medikament gegen Husten.", level: "A2", category: "Arzt" },
  { id: "s18", arabic: "سأذهب إلى الصيدلية الآن.", german: "Ich gehe jetzt zur Apotheke.", level: "A1", category: "Arzt" },
  { id: "s19", arabic: "الطبيب قال إن كل شيء جيد.", german: "Der Arzt sagte, dass alles gut ist.", level: "A2", category: "Arzt" },
  { id: "s20", arabic: "لدي موعد طبي يوم الاثنين.", german: "Ich habe am Montag einen Arzttermin.", level: "A2", category: "Arzt" },
  { id: "s21", arabic: "الشقة قريبة من العمل.", german: "Die Wohnung ist nah an der Arbeit.", level: "A1", category: "Wohnung" },
  { id: "s22", arabic: "المطبخ كبير ومضيء.", german: "Die Küche ist groß und hell.", level: "A1", category: "Wohnung" },
  { id: "s23", arabic: "الإيجار يشمل الكهرباء.", german: "Die Miete beinhaltet den Strom.", level: "A2", category: "Wohnung" },
  { id: "s24", arabic: "هل يمكنني فتح النافذة؟", german: "Kann ich das Fenster öffnen?", level: "A1", category: "Wohnung" },
  { id: "s25", arabic: "الغرفة تحتاج إلى أثاث جديد.", german: "Das Zimmer braucht neue Möbel.", level: "A2", category: "Wohnung" },
  { id: "s26", arabic: "ما هو الوقت الآن؟", german: "Wie spät ist es?", level: "A1", category: "Alltag" },
  { id: "s27", arabic: "أحب القراءة في المساء.", german: "Ich lese gern am Abend.", level: "A1", category: "Alltag" },
  { id: "s28", arabic: "أريد أن أمارس اللغة مع صديق.", german: "Ich möchte mit einem Freund üben.", level: "A2", category: "Alltag" },
  { id: "s29", arabic: "هل يمكنني الحصول على غرفة مفردة؟", german: "Kann ich ein Einzelzimmer bekommen?", level: "A2", category: "Wohnung" },
  { id: "s30", arabic: "أشرب الشاي بعد الغداء.", german: "Ich trinke Tee nach dem Mittagessen.", level: "A1", category: "Essen" }
];
