const vocabulary = [
  { id: "v1", arabic: "تجربة", german: "Erfahrung", article: "die", plural: "Erfahrungen", example_de: "Die Erfahrung hilft mir im Alltag.", example_ar: "التجربة تساعدني في الحياة اليومية.", level: "B1", category: "Alltag" },
  { id: "v2", arabic: "تحدي", german: "Herausforderung", article: "die", plural: "Herausforderungen", example_de: "Die Herausforderung motiviert mich.", example_ar: "التحدي يحفزني.", level: "B1", category: "Alltag" },
  { id: "v3", arabic: "قرار", german: "Entscheidung", article: "die", plural: "Entscheidungen", example_de: "Ich treffe eine wichtige Entscheidung.", example_ar: "أتخذ قرارًا مهمًا.", level: "B1", category: "Alltag" },
  { id: "v4", arabic: "تغيير", german: "Veränderung", article: "die", plural: "Veränderungen", example_de: "Die Veränderung war positiv.", example_ar: "كان التغيير إيجابيًا.", level: "B1", category: "Alltag" },
  { id: "v5", arabic: "موعد", german: "Verabredung", article: "die", plural: "Verabredungen", example_de: "Wir haben eine Verabredung am Abend.", example_ar: "لدينا موعد مساءً.", level: "B1", category: "Alltag" },
  { id: "v6", arabic: "نصيحة", german: "Ratschlag", article: "der", plural: "Ratschläge", example_de: "Danke für deinen Ratschlag.", example_ar: "شكرًا على نصيحتك.", level: "B1", category: "Alltag" },
  { id: "v7", arabic: "ثقة", german: "Vertrauen", article: "das", plural: "-", example_de: "Vertrauen ist wichtig.", example_ar: "الثقة مهمة.", level: "B1", category: "Alltag" },
  { id: "v8", arabic: "طموح", german: "Ziel", article: "das", plural: "Ziele", example_de: "Mein Ziel ist fließend zu sprechen.", example_ar: "هدفي أن أتحدث بطلاقة.", level: "B1", category: "Alltag" },
  { id: "v9", arabic: "عادة", german: "Gewohnheit", article: "die", plural: "Gewohnheiten", example_de: "Eine gute Gewohnheit spart Zeit.", example_ar: "العادة الجيدة توفر الوقت.", level: "B1", category: "Alltag" },
  { id: "v10", arabic: "أمان", german: "Sicherheit", article: "die", plural: "Sicherheiten", example_de: "Ich brauche Sicherheit im Leben.", example_ar: "أحتاج إلى الأمان في الحياة.", level: "B1", category: "Alltag" },
  { id: "v11", arabic: "توقع", german: "Erwartung", article: "die", plural: "Erwartungen", example_de: "Die Erwartungen sind hoch.", example_ar: "التوقعات عالية.", level: "B1", category: "Alltag" },
  { id: "v12", arabic: "تحضير", german: "Vorbereitung", article: "die", plural: "Vorbereitungen", example_de: "Die Vorbereitung dauert eine Stunde.", example_ar: "التحضير يستغرق ساعة.", level: "B1", category: "Alltag" },
  { id: "v13", arabic: "مكونات", german: "Zutaten", article: "die", plural: "Zutaten", example_de: "Die Zutaten sind frisch.", example_ar: "المكونات طازجة.", level: "B1", category: "Essen" },
  { id: "v14", arabic: "وجبة خفيفة", german: "Snack", article: "der", plural: "Snacks", example_de: "Am Nachmittag esse ich einen Snack.", example_ar: "بعد الظهر آكل وجبة خفيفة.", level: "B1", category: "Essen" },
  { id: "v15", arabic: "شهية", german: "Appetit", article: "der", plural: "-", example_de: "Ich habe keinen Appetit.", example_ar: "لا شهية لدي.", level: "B1", category: "Essen" },
  { id: "v16", arabic: "نظام غذائي", german: "Ernährung", article: "die", plural: "Ernährungen", example_de: "Eine gesunde Ernährung ist wichtig.", example_ar: "التغذية الصحية مهمة.", level: "B1", category: "Essen" },
  { id: "v17", arabic: "توصية", german: "Empfehlung", article: "die", plural: "Empfehlungen", example_de: "Die Empfehlung des Kochs ist gut.", example_ar: "توصية الطاهي جيدة.", level: "B1", category: "Essen" },
  { id: "v18", arabic: "تقليل", german: "Reduktion", article: "die", plural: "Reduktionen", example_de: "Ich mache eine Reduktion von Zucker.", example_ar: "أقوم بتقليل السكر.", level: "B1", category: "Essen" },
  { id: "v19", arabic: "حساسية", german: "Allergie", article: "die", plural: "Allergien", example_de: "Ich habe eine Allergie gegen Nüsse.", example_ar: "لدي حساسية من المكسرات.", level: "B1", category: "Essen" },
  { id: "v20", arabic: "مشاركة", german: "Portion", article: "die", plural: "Portionen", example_de: "Eine Portion reicht für zwei.", example_ar: "الحصة تكفي لشخصين.", level: "B1", category: "Essen" },
  { id: "v21", arabic: "مذاق", german: "Geschmack", article: "der", plural: "Geschmäcker", example_de: "Der Geschmack ist intensiv.", example_ar: "الطعم قوي.", level: "B1", category: "Essen" },
  { id: "v22", arabic: "وجبة خاصة", german: "Spezialität", article: "die", plural: "Spezialitäten", example_de: "Die Spezialität des Hauses ist beliebt.", example_ar: "تخصص المطعم محبوب.", level: "B1", category: "Essen" },
  { id: "v23", arabic: "حجز", german: "Reservierung", article: "die", plural: "Reservierungen", example_de: "Ich habe eine Reservierung um acht.", example_ar: "لدي حجز الساعة الثامنة.", level: "B1", category: "Essen" },
  { id: "v24", arabic: "مطبخ نباتي", german: "Vegetarische Küche", article: "die", plural: "-", example_de: "Vegetarische Küche wird hier angeboten.", example_ar: "يتم تقديم المطبخ النباتي هنا.", level: "B1", category: "Essen" },
  { id: "v25", arabic: "ترقية", german: "Beförderung", article: "die", plural: "Beförderungen", example_de: "Sie wartet auf eine Beförderung.", example_ar: "هي تنتظر ترقية.", level: "B1", category: "Arbeit" },
  { id: "v26", arabic: "مسؤولية", german: "Verantwortung", article: "die", plural: "Verantwortungen", example_de: "Ich trage viel Verantwortung.", example_ar: "أتحمل مسؤولية كبيرة.", level: "B1", category: "Arbeit" },
  { id: "v27", arabic: "مفاوضة", german: "Verhandlung", article: "die", plural: "Verhandlungen", example_de: "Die Verhandlung dauert lange.", example_ar: "المفاوضة تستغرق وقتًا طويلًا.", level: "B1", category: "Arbeit" },
  { id: "v28", arabic: "اتفاق", german: "Vereinbarung", article: "die", plural: "Vereinbarungen", example_de: "Wir haben eine Vereinbarung getroffen.", example_ar: "توصلنا إلى اتفاق.", level: "B1", category: "Arbeit" },
  { id: "v29", arabic: "أولوية", german: "Priorität", article: "die", plural: "Prioritäten", example_de: "Das hat heute Priorität.", example_ar: "هذا له أولوية اليوم.", level: "B1", category: "Arbeit" },
  { id: "v30", arabic: "تنسيق", german: "Abstimmung", article: "die", plural: "Abstimmungen", example_de: "Wir brauchen eine Abstimmung im Team.", example_ar: "نحتاج إلى تنسيق في الفريق.", level: "B1", category: "Arbeit" },
  { id: "v31", arabic: "إنتاجية", german: "Produktivität", article: "die", plural: "-", example_de: "Die Produktivität ist gestiegen.", example_ar: "زادت الإنتاجية.", level: "B1", category: "Arbeit" },
  { id: "v32", arabic: "تقرير", german: "Bericht", article: "der", plural: "Berichte", example_de: "Der Bericht ist fertig.", example_ar: "التقرير جاهز.", level: "B1", category: "Arbeit" },
  { id: "v33", arabic: "موعد نهائي", german: "Frist", article: "die", plural: "Fristen", example_de: "Die Frist endet am Freitag.", example_ar: "الموعد النهائي ينتهي يوم الجمعة.", level: "B1", category: "Arbeit" },
  { id: "v34", arabic: "مبادرة", german: "Initiative", article: "die", plural: "Initiativen", example_de: "Sie zeigt viel Initiative.", example_ar: "هي تبدي الكثير من المبادرة.", level: "B1", category: "Arbeit" },
  { id: "v35", arabic: "مقابلة عمل", german: "Bewerbungsgespräch", article: "das", plural: "Bewerbungsgespräche", example_de: "Das Bewerbungsgespräch war erfolgreich.", example_ar: "مقابلة العمل كانت ناجحة.", level: "B1", category: "Arbeit" },
  { id: "v36", arabic: "تدريب", german: "Fortbildung", article: "die", plural: "Fortbildungen", example_de: "Ich mache eine Fortbildung.", example_ar: "أقوم بتدريب متقدم.", level: "B1", category: "Arbeit" },
  { id: "v37", arabic: "تشخيص", german: "Diagnose", article: "die", plural: "Diagnosen", example_de: "Die Diagnose kommt morgen.", example_ar: "سيأتي التشخيص غدًا.", level: "B1", category: "Arzt" },
  { id: "v38", arabic: "موعد عاجل", german: "Notfall", article: "der", plural: "Notfälle", example_de: "Das ist ein Notfall.", example_ar: "هذه حالة طارئة.", level: "B1", category: "Arzt" },
  { id: "v39", arabic: "تأمين صحي", german: "Krankenversicherung", article: "die", plural: "Krankenversicherungen", example_de: "Die Krankenversicherung ist notwendig.", example_ar: "التأمين الصحي ضروري.", level: "B1", category: "Arzt" },
  { id: "v40", arabic: "وصفة طبية", german: "Verschreibung", article: "die", plural: "Verschreibungen", example_de: "Ich brauche eine Verschreibung.", example_ar: "أحتاج إلى وصفة طبية.", level: "B1", category: "Arzt" },
  { id: "v41", arabic: "أعراض", german: "Symptome", article: "die", plural: "Symptome", example_de: "Die Symptome sind stärker geworden.", example_ar: "ازدادت الأعراض.", level: "B1", category: "Arzt" },
  { id: "v42", arabic: "ضغط الدم", german: "Blutdruck", article: "der", plural: "Blutdrücke", example_de: "Der Blutdruck ist zu hoch.", example_ar: "ضغط الدم مرتفع جدًا.", level: "B1", category: "Arzt" },
  { id: "v43", arabic: "إجازة مرضية", german: "Krankschreibung", article: "die", plural: "Krankschreibungen", example_de: "Ich brauche eine Krankschreibung.", example_ar: "أحتاج إلى إجازة مرضية.", level: "B1", category: "Arzt" },
  { id: "v44", arabic: "فحص طبي", german: "Check-up", article: "der", plural: "Check-ups", example_de: "Der Check-up war unauffällig.", example_ar: "الفحص الطبي كان طبيعيًا.", level: "B1", category: "Arzt" },
  { id: "v45", arabic: "علاج طبيعي", german: "Physiotherapie", article: "die", plural: "Physiotherapien", example_de: "Die Physiotherapie hilft dem Rücken.", example_ar: "العلاج الطبيعي يساعد الظهر.", level: "B1", category: "Arzt" },
  { id: "v46", arabic: "نموذج", german: "Formular", article: "das", plural: "Formulare", example_de: "Bitte füllen Sie das Formular aus.", example_ar: "يرجى ملء النموذج.", level: "B1", category: "Arzt" },
  { id: "v47", arabic: "تطعيم", german: "Impfung", article: "die", plural: "Impfungen", example_de: "Die Impfung ist kostenlos.", example_ar: "التطعيم مجاني.", level: "B1", category: "Arzt" },
  { id: "v48", arabic: "شفاء", german: "Genesung", article: "die", plural: "-", example_de: "Die Genesung dauert ein paar Wochen.", example_ar: "الشفاء يستغرق بضعة أسابيع.", level: "B1", category: "Arzt" },
  { id: "v49", arabic: "صيانة", german: "Instandhaltung", article: "die", plural: "Instandhaltungen", example_de: "Die Instandhaltung kostet Geld.", example_ar: "الصيانة تكلف المال.", level: "B1", category: "Wohnung" },
  { id: "v50", arabic: "عقد إيجار", german: "Mietvertrag", article: "der", plural: "Mietverträge", example_de: "Ich unterschreibe den Mietvertrag.", example_ar: "أوقع عقد الإيجار.", level: "B1", category: "Wohnung" },
  { id: "v51", arabic: "وديعة", german: "Kaution", article: "die", plural: "Kautionen", example_de: "Die Kaution ist hoch.", example_ar: "الوديعة مرتفعة.", level: "B1", category: "Wohnung" },
  { id: "v52", arabic: "أجهزة", german: "Haushaltsgeräte", article: "die", plural: "Haushaltsgeräte", example_de: "Die Haushaltsgeräte sind neu.", example_ar: "الأجهزة المنزلية جديدة.", level: "B1", category: "Wohnung" },
  { id: "v53", arabic: "إضاءة", german: "Beleuchtung", article: "die", plural: "Beleuchtungen", example_de: "Die Beleuchtung ist angenehm.", example_ar: "الإضاءة مريحة.", level: "B1", category: "Wohnung" },
  { id: "v54", arabic: "جيران", german: "Nachbarschaft", article: "die", plural: "Nachbarschaften", example_de: "Die Nachbarschaft ist ruhig.", example_ar: "الحي هادئ.", level: "B1", category: "Wohnung" },
  { id: "v55", arabic: "مساحة", german: "Wohnfläche", article: "die", plural: "Wohnflächen", example_de: "Die Wohnfläche beträgt 80 Quadratmeter.", example_ar: "مساحة السكن 80 مترًا مربعًا.", level: "B1", category: "Wohnung" },
  { id: "v56", arabic: "تأثيث", german: "Möblierung", article: "die", plural: "Möblierungen", example_de: "Die Möblierung ist modern.", example_ar: "التأثيث حديث.", level: "B1", category: "Wohnung" },
  { id: "v57", arabic: "سلم", german: "Treppenhaus", article: "das", plural: "Treppenhäuser", example_de: "Das Treppenhaus wird gereinigt.", example_ar: "يتم تنظيف الدرج.", level: "B1", category: "Wohnung" },
  { id: "v58", arabic: "عداد", german: "Zähler", article: "der", plural: "Zähler", example_de: "Der Zählerstand wird abgelesen.", example_ar: "يتم قراءة العداد.", level: "B1", category: "Wohnung" },
  { id: "v59", arabic: "خدمات إضافية", german: "Nebenkosten", article: "die", plural: "Nebenkosten", example_de: "Die Nebenkosten sind gestiegen.", example_ar: "زادت التكاليف الإضافية.", level: "B1", category: "Wohnung" },
  { id: "v60", arabic: "إصلاح", german: "Reparatur", article: "die", plural: "Reparaturen", example_de: "Die Reparatur dauert zwei Tage.", example_ar: "الإصلاح يستغرق يومين.", level: "B1", category: "Wohnung" },
  { id: "v61", arabic: "انضباط ذاتي", german: "Selbstdisziplin", article: "die", plural: "-", example_de: "Selbstdisziplin hilft beim Lernen.", example_ar: "الانضباط الذاتي يساعد في التعلم.", level: "B2", category: "Alltag" },
  { id: "v62", arabic: "موازنة", german: "Abwägung", article: "die", plural: "Abwägungen", example_de: "Eine Abwägung der Optionen ist nötig.", example_ar: "موازنة الخيارات ضرورية.", level: "B2", category: "Alltag" },
  { id: "v63", arabic: "موثوقية", german: "Verlässlichkeit", article: "die", plural: "-", example_de: "Verlässlichkeit schafft Vertrauen.", example_ar: "الموثوقية تبني الثقة.", level: "B2", category: "Alltag" },
  { id: "v64", arabic: "تقييم أولويات", german: "Priorisierung", article: "die", plural: "Priorisierungen", example_de: "Priorisierung spart Zeit im Alltag.", example_ar: "تقييم الأولويات يوفر الوقت في الحياة اليومية.", level: "B2", category: "Alltag" },
  { id: "v65", arabic: "توجيه", german: "Orientierung", article: "die", plural: "-", example_de: "Orientierung hilft in neuen Situationen.", example_ar: "التوجيه يساعد في المواقف الجديدة.", level: "B2", category: "Alltag" },
  { id: "v66", arabic: "منظور", german: "Perspektive", article: "die", plural: "Perspektiven", example_de: "Eine neue Perspektive motiviert mich.", example_ar: "منظور جديد يحفزني.", level: "B2", category: "Alltag" },
  { id: "v67", arabic: "ترابط", german: "Zusammenhang", article: "der", plural: "Zusammenhänge", example_de: "Der Zusammenhang ist deutlich.", example_ar: "العلاقة واضحة.", level: "B2", category: "Alltag" },
  { id: "v68", arabic: "تأثير", german: "Einfluss", article: "der", plural: "Einflüsse", example_de: "Der Einfluss der Medien ist groß.", example_ar: "تأثير الإعلام كبير.", level: "B2", category: "Alltag" },
  { id: "v69", arabic: "هدوء", german: "Gelassenheit", article: "die", plural: "-", example_de: "Gelassenheit hilft in stressigen Zeiten.", example_ar: "الهدوء يساعد في الأوقات المجهدة.", level: "B2", category: "Alltag" },
  { id: "v70", arabic: "ثبات", german: "Konsequenz", article: "die", plural: "Konsequenzen", example_de: "Konsequenz zeigt sich im Alltag.", example_ar: "الثبات يظهر في الحياة اليومية.", level: "B2", category: "Alltag" },
  { id: "v71", arabic: "طريقة التحضير", german: "Zubereitungsart", article: "die", plural: "Zubereitungsarten", example_de: "Die Zubereitungsart beeinflusst den Geschmack.", example_ar: "طريقة التحضير تؤثر على الطعم.", level: "B2", category: "Essen" },
  { id: "v72", arabic: "قيمة غذائية", german: "Nährwert", article: "der", plural: "Nährwerte", example_de: "Der Nährwert ist bei Salaten hoch.", example_ar: "القيمة الغذائية في السلطات عالية.", level: "B2", category: "Essen" },
  { id: "v73", arabic: "حفظ الطعام", german: "Konservierung", article: "die", plural: "Konservierungen", example_de: "Konservierung verlängert die Haltbarkeit.", example_ar: "حفظ الطعام يطيل مدة الصلاحية.", level: "B2", category: "Essen" },
  { id: "v74", arabic: "نكهة دقيقة", german: "Geschmacksnote", article: "die", plural: "Geschmacksnoten", example_de: "Die Geschmacksnote ist leicht nussig.", example_ar: "النكهة دقيقة وتميل للمكسرات.", level: "B2", category: "Essen" },
  { id: "v75", arabic: "منتج موسمي", german: "Saisonprodukt", article: "das", plural: "Saisonprodukte", example_de: "Saisonprodukte schmecken oft intensiver.", example_ar: "المنتجات الموسمية مذاقها أقوى.", level: "B2", category: "Essen" },
  { id: "v76", arabic: "استغلال البقايا", german: "Resteverwertung", article: "die", plural: "Resteverwertungen", example_de: "Resteverwertung spart Geld.", example_ar: "استغلال البقايا يوفر المال.", level: "B2", category: "Essen" },
  { id: "v77", arabic: "قائمة المكونات", german: "Zutatenliste", article: "die", plural: "Zutatenlisten", example_de: "Die Zutatenliste ist verständlich.", example_ar: "قائمة المكونات واضحة.", level: "B2", category: "Essen" },
  { id: "v78", arabic: "قدرة التحمل", german: "Verträglichkeit", article: "die", plural: "Verträglichkeiten", example_de: "Die Verträglichkeit ist gut.", example_ar: "قدرة التحمل جيدة.", level: "B2", category: "Essen" },
  { id: "v79", arabic: "حجم الحصة", german: "Portionsgröße", article: "die", plural: "Portionsgrößen", example_de: "Die Portionsgröße ist ausreichend.", example_ar: "حجم الحصة كافٍ.", level: "B2", category: "Essen" },
  { id: "v80", arabic: "توازن السعرات", german: "Kalorienbalance", article: "die", plural: "Kalorienbalancen", example_de: "Kalorienbalance ist wichtig.", example_ar: "توازن السعرات مهم.", level: "B2", category: "Essen" },
  { id: "v81", arabic: "تخطيط الموارد", german: "Ressourcenplanung", article: "die", plural: "Ressourcenplanungen", example_de: "Ressourcenplanung verhindert Engpässe.", example_ar: "تخطيط الموارد يمنع النقص.", level: "B2", category: "Arbeit" },
  { id: "v82", arabic: "مرحلة المشروع", german: "Projektphase", article: "die", plural: "Projektphasen", example_de: "Wir sind in der ersten Projektphase.", example_ar: "نحن في المرحلة الأولى من المشروع.", level: "B2", category: "Arbeit" },
  { id: "v83", arabic: "تنظيم الساعات الإضافية", german: "Überstundenregelung", article: "die", plural: "Überstundenregelungen", example_de: "Die Überstundenregelung ist klar.", example_ar: "تنظيم الساعات الإضافية واضح.", level: "B2", category: "Arbeit" },
  { id: "v84", arabic: "إثبات الأداء", german: "Leistungsnachweis", article: "der", plural: "Leistungsnachweise", example_de: "Der Leistungsnachweis ist erforderlich.", example_ar: "إثبات الأداء مطلوب.", level: "B2", category: "Arbeit" },
  { id: "v85", arabic: "مرحلة مهمة", german: "Meilenstein", article: "der", plural: "Meilensteine", example_de: "Wir haben den ersten Meilenstein erreicht.", example_ar: "وصلنا إلى أول مرحلة مهمة.", level: "B2", category: "Arbeit" },
  { id: "v86", arabic: "تنسيق الفريق", german: "Teamkoordination", article: "die", plural: "Teamkoordinationen", example_de: "Teamkoordination spart Zeit.", example_ar: "تنسيق الفريق يوفر الوقت.", level: "B2", category: "Arbeit" },
  { id: "v87", arabic: "هدف محدد", german: "Zielvorgabe", article: "die", plural: "Zielvorgaben", example_de: "Die Zielvorgabe ist klar.", example_ar: "الهدف المحدد واضح.", level: "B2", category: "Arbeit" },
  { id: "v88", arabic: "سير العمل", german: "Arbeitsablauf", article: "der", plural: "Arbeitsabläufe", example_de: "Der Arbeitsablauf ist strukturiert.", example_ar: "سير العمل منظم.", level: "B2", category: "Arbeit" },
  { id: "v89", arabic: "تحليل المخاطر", german: "Risikoanalyse", article: "die", plural: "Risikoanalysen", example_de: "Die Risikoanalyse zeigt Schwachstellen.", example_ar: "تحليل المخاطر يوضح نقاط الضعف.", level: "B2", category: "Arbeit" },
  { id: "v90", arabic: "تحسين العمليات", german: "Prozessoptimierung", article: "die", plural: "Prozessoptimierungen", example_de: "Prozessoptimierung verbessert die Qualität.", example_ar: "تحسين العمليات يرفع الجودة.", level: "B2", category: "Arbeit" },
  { id: "v91", arabic: "مسار العلاج", german: "Therapieverlauf", article: "der", plural: "Therapieverläufe", example_de: "Der Therapieverlauf wird dokumentiert.", example_ar: "مسار العلاج يتم توثيقه.", level: "B2", category: "Arzt" },
  { id: "v92", arabic: "تأثير طويل الأمد", german: "Langzeitwirkung", article: "die", plural: "Langzeitwirkungen", example_de: "Die Langzeitwirkung ist positiv.", example_ar: "التأثير طويل الأمد إيجابي.", level: "B2", category: "Arzt" },
  { id: "v93", arabic: "جدول التطعيم", german: "Impfschema", article: "das", plural: "Impfschemata", example_de: "Das Impfschema wird erklärt.", example_ar: "جدول التطعيم يتم شرحه.", level: "B2", category: "Arzt" },
  { id: "v94", arabic: "رعاية لاحقة", german: "Nachsorge", article: "die", plural: "-", example_de: "Die Nachsorge ist wichtig.", example_ar: "الرعاية اللاحقة مهمة.", level: "B2", category: "Arzt" },
  { id: "v95", arabic: "رأي ثانٍ", german: "Zweitmeinung", article: "die", plural: "Zweitmeinungen", example_de: "Ich hole eine Zweitmeinung ein.", example_ar: "أحصل على رأي ثانٍ.", level: "B2", category: "Arzt" },
  { id: "v96", arabic: "توضيح طبي", german: "Aufklärung", article: "die", plural: "Aufklärungen", example_de: "Die Aufklärung vor der OP ist wichtig.", example_ar: "التوضيح الطبي قبل العملية مهم.", level: "B2", category: "Arzt" },
  { id: "v97", arabic: "خطة علاج", german: "Behandlungsplan", article: "der", plural: "Behandlungspläne", example_de: "Der Behandlungsplan wird besprochen.", example_ar: "خطة العلاج تتم مناقشتها.", level: "B2", category: "Arzt" },
  { id: "v98", arabic: "إعادة تأهيل", german: "Rehabilitation", article: "die", plural: "Rehabilitationen", example_de: "Die Rehabilitation dauert mehrere Wochen.", example_ar: "إعادة التأهيل تستغرق عدة أسابيع.", level: "B2", category: "Arzt" },
  { id: "v99", arabic: "إحالة طبية", german: "Überweisung", article: "die", plural: "Überweisungen", example_de: "Ich brauche eine Überweisung.", example_ar: "أحتاج إلى إحالة طبية.", level: "B2", category: "Arzt" },
  { id: "v100", arabic: "أثر جانبي", german: "Nebenwirkung", article: "die", plural: "Nebenwirkungen", example_de: "Die Nebenwirkung ist bekannt.", example_ar: "الأثر الجانبي معروف.", level: "B2", category: "Arzt" },
  { id: "v101", arabic: "مؤشر الإيجارات", german: "Mietspiegel", article: "der", plural: "Mietspiegel", example_de: "Der Mietspiegel zeigt die Preise.", example_ar: "مؤشر الإيجارات يوضح الأسعار.", level: "B2", category: "Wohnung" },
  { id: "v102", arabic: "ترخيص البناء", german: "Baugenehmigung", article: "die", plural: "Baugenehmigungen", example_de: "Die Baugenehmigung liegt vor.", example_ar: "ترخيص البناء متوفر.", level: "B2", category: "Wohnung" },
  { id: "v103", arabic: "عزل صوتي", german: "Schallschutz", article: "der", plural: "Schallschutzmaßnahmen", example_de: "Guter Schallschutz verbessert den Komfort.", example_ar: "العزل الصوتي الجيد يحسن الراحة.", level: "B2", category: "Wohnung" },
  { id: "v104", arabic: "مفهوم سكني", german: "Wohnkonzept", article: "das", plural: "Wohnkonzepte", example_de: "Das Wohnkonzept ist offen gestaltet.", example_ar: "المفهوم السكني مصمم بشكل مفتوح.", level: "B2", category: "Wohnung" },
  { id: "v105", arabic: "عزل حراري", german: "Dämmung", article: "die", plural: "Dämmungen", example_de: "Die Dämmung senkt die Heizkosten.", example_ar: "العزل يقلل تكاليف التدفئة.", level: "B2", category: "Wohnung" },
  { id: "v106", arabic: "تهوية", german: "Belüftung", article: "die", plural: "Belüftungen", example_de: "Gute Belüftung verhindert Schimmel.", example_ar: "التهوية الجيدة تمنع العفن.", level: "B2", category: "Wohnung" },
  { id: "v107", arabic: "عفن", german: "Schimmel", article: "der", plural: "Schimmel", example_de: "Der Schimmel muss entfernt werden.", example_ar: "يجب إزالة العفن.", level: "B2", category: "Wohnung" },
  { id: "v108", arabic: "مخطط", german: "Grundriss", article: "der", plural: "Grundrisse", example_de: "Der Grundriss ist offen.", example_ar: "المخطط مفتوح.", level: "B2", category: "Wohnung" },
  { id: "v109", arabic: "شرفة علوية", german: "Dachterrasse", article: "die", plural: "Dachterrassen", example_de: "Die Dachterrasse bietet viel Sonne.", example_ar: "السطح يوفر الكثير من الشمس.", level: "B2", category: "Wohnung" },
  { id: "v110", arabic: "تجهيز ذكي", german: "Smart-Home-System", article: "das", plural: "Smart-Home-Systeme", example_de: "Das Smart-Home-System spart Energie.", example_ar: "نظام المنزل الذكي يوفر الطاقة.", level: "B2", category: "Wohnung" },
  { id: "v111", arabic: "تغير القيم", german: "Wertewandel", article: "der", plural: "Wertewandel", example_de: "Ein Wertewandel beeinflusst die Gesellschaft.", example_ar: "تغير القيم يؤثر على المجتمع.", level: "C1", category: "Alltag" },
  { id: "v112", arabic: "وعي الاستدامة", german: "Nachhaltigkeitsbewusstsein", article: "das", plural: "-", example_de: "Nachhaltigkeitsbewusstsein wächst stetig.", example_ar: "وعي الاستدامة يتزايد باستمرار.", level: "C1", category: "Alltag" },
  { id: "v113", arabic: "مشاركة مجتمعية", german: "Gesellschaftsbeteiligung", article: "die", plural: "-", example_de: "Gesellschaftsbeteiligung stärkt den Zusammenhalt.", example_ar: "المشاركة المجتمعية تقوي التماسك.", level: "C1", category: "Alltag" },
  { id: "v114", arabic: "تصور الحياة", german: "Lebensentwurf", article: "der", plural: "Lebensentwürfe", example_de: "Der Lebensentwurf verändert sich mit der Zeit.", example_ar: "تصور الحياة يتغير مع الوقت.", level: "C1", category: "Alltag" },
  { id: "v115", arabic: "اعتماد", german: "Abhängigkeit", article: "die", plural: "Abhängigkeiten", example_de: "Abhängigkeit kann problematisch sein.", example_ar: "الاعتماد قد يكون مشكلة.", level: "C1", category: "Alltag" },
  { id: "v116", arabic: "تساؤل", german: "Fragestellung", article: "die", plural: "Fragestellungen", example_de: "Die Fragestellung ist klar formuliert.", example_ar: "صياغة السؤال واضحة.", level: "C1", category: "Alltag" },
  { id: "v117", arabic: "تقنين", german: "Regulierung", article: "die", plural: "Regulierungen", example_de: "Die Regulierung schützt Verbraucher.", example_ar: "التنظيم يحمي المستهلكين.", level: "C1", category: "Alltag" },
  { id: "v118", arabic: "تماسك", german: "Kohärenz", article: "die", plural: "-", example_de: "Kohärenz stärkt die Argumentation.", example_ar: "التماسك يقوي الحجة.", level: "C1", category: "Alltag" },
  { id: "v119", arabic: "مرونة نفسية", german: "Resilienz", article: "die", plural: "-", example_de: "Resilienz hilft bei Belastung.", example_ar: "المرونة النفسية تساعد عند الضغوط.", level: "C1", category: "Alltag" },
  { id: "v120", arabic: "بُعد نظر", german: "Weitblick", article: "der", plural: "-", example_de: "Weitblick erleichtert Entscheidungen.", example_ar: "بعد النظر يسهل القرارات.", level: "C1", category: "Alltag" },
  { id: "v121", arabic: "ثقافة الطعام", german: "Ernährungskultur", article: "die", plural: "Ernährungskulturen", example_de: "Ernährungskultur prägt die Küche.", example_ar: "ثقافة الطعام تشكل المطبخ.", level: "C1", category: "Essen" },
  { id: "v122", arabic: "مصدر المكونات", german: "Zutatenherkunft", article: "die", plural: "Zutatenherkünfte", example_de: "Die Zutatenherkunft ist transparent.", example_ar: "مصدر المكونات واضح.", level: "C1", category: "Essen" },
  { id: "v123", arabic: "تعقيد النكهة", german: "Geschmackskomplexität", article: "die", plural: "Geschmackskomplexitäten", example_de: "Die Geschmackskomplexität ist beeindruckend.", example_ar: "تعقيد النكهة مثير للإعجاب.", level: "C1", category: "Essen" },
  { id: "v124", arabic: "تخمير", german: "Fermentation", article: "die", plural: "Fermentationen", example_de: "Fermentation verbessert das Aroma.", example_ar: "التخمير يحسن النكهة.", level: "C1", category: "Essen" },
  { id: "v125", arabic: "مأكولات فاخرة", german: "Feinkost", article: "die", plural: "Feinkost", example_de: "Feinkost wird hier frisch angeboten.", example_ar: "المأكولات الفاخرة تقدم هنا طازجة.", level: "C1", category: "Essen" },
  { id: "v126", arabic: "وسم المواد المسببة للحساسية", german: "Allergenkennzeichnung", article: "die", plural: "-", example_de: "Die Allergenkennzeichnung ist Pflicht.", example_ar: "وسم المواد المسببة للحساسية إلزامي.", level: "C1", category: "Essen" },
  { id: "v127", arabic: "معيار الجودة", german: "Qualitätsstandard", article: "der", plural: "Qualitätsstandards", example_de: "Der Qualitätsstandard ist hoch.", example_ar: "معيار الجودة مرتفع.", level: "C1", category: "Essen" },
  { id: "v128", arabic: "سلسلة الإنتاج", german: "Produktionskette", article: "die", plural: "Produktionsketten", example_de: "Die Produktionskette ist nachvollziehbar.", example_ar: "سلسلة الإنتاج واضحة.", level: "C1", category: "Essen" },
  { id: "v129", arabic: "فن الطهي", german: "Kulinarik", article: "die", plural: "-", example_de: "Kulinarik spiegelt die Kultur.", example_ar: "فن الطهي يعكس الثقافة.", level: "C1", category: "Essen" },
  { id: "v130", arabic: "حاسة التذوق", german: "Sensorik", article: "die", plural: "-", example_de: "Sensorik spielt eine wichtige Rolle.", example_ar: "حاسة التذوق تلعب دورًا مهمًا.", level: "C1", category: "Essen" },
  { id: "v131", arabic: "استراتيجية الشركة", german: "Unternehmensstrategie", article: "die", plural: "Unternehmensstrategien", example_de: "Die Unternehmensstrategie wird angepasst.", example_ar: "استراتيجية الشركة يتم تعديلها.", level: "C1", category: "Arbeit" },
  { id: "v132", arabic: "أصحاب المصلحة", german: "Stakeholder", article: "der", plural: "Stakeholder", example_de: "Stakeholder erwarten klare Ziele.", example_ar: "أصحاب المصلحة يتوقعون أهدافًا واضحة.", level: "C1", category: "Arbeit" },
  { id: "v133", arabic: "تفاوض عقد", german: "Vertragsverhandlung", article: "die", plural: "Vertragsverhandlungen", example_de: "Die Vertragsverhandlung war intensiv.", example_ar: "تفاوض العقد كان مكثفًا.", level: "C1", category: "Arbeit" },
  { id: "v134", arabic: "إدارة النزاعات", german: "Konfliktmanagement", article: "das", plural: "-", example_de: "Konfliktmanagement verbessert die Zusammenarbeit.", example_ar: "إدارة النزاعات تحسن التعاون.", level: "C1", category: "Arbeit" },
  { id: "v135", arabic: "قدرة تنافسية", german: "Wettbewerbsfähigkeit", article: "die", plural: "-", example_de: "Wettbewerbsfähigkeit bleibt wichtig.", example_ar: "القدرة التنافسية تبقى مهمة.", level: "C1", category: "Arbeit" },
  { id: "v136", arabic: "محرك الابتكار", german: "Innovationstreiber", article: "der", plural: "Innovationstreiber", example_de: "Innovationstreiber fördern Wachstum.", example_ar: "محركات الابتكار تعزز النمو.", level: "C1", category: "Arbeit" },
  { id: "v137", arabic: "تقرير الاستدامة", german: "Nachhaltigkeitsbericht", article: "der", plural: "Nachhaltigkeitsberichte", example_de: "Der Nachhaltigkeitsbericht ist öffentlich.", example_ar: "تقرير الاستدامة متاح للعامة.", level: "C1", category: "Arbeit" },
  { id: "v138", arabic: "ملف المخاطر", german: "Risikoprofil", article: "das", plural: "Risikoprofile", example_de: "Das Risikoprofil wird geprüft.", example_ar: "ملف المخاطر يتم فحصه.", level: "C1", category: "Arbeit" },
  { id: "v139", arabic: "كفاءة القيادة", german: "Führungskompetenz", article: "die", plural: "-", example_de: "Führungskompetenz stärkt Teams.", example_ar: "كفاءة القيادة تقوي الفرق.", level: "C1", category: "Arbeit" },
  { id: "v140", arabic: "عملية تحول", german: "Transformationsprozess", article: "der", plural: "Transformationsprozesse", example_de: "Der Transformationsprozess dauert Jahre.", example_ar: "عملية التحول تستغرق سنوات.", level: "C1", category: "Arbeit" },
  { id: "v141", arabic: "الالتزام بالعلاج", german: "Therapieadhärenz", article: "die", plural: "-", example_de: "Therapieadhärenz beeinflusst den Erfolg.", example_ar: "الالتزام بالعلاج يؤثر على النجاح.", level: "C1", category: "Arzt" },
  { id: "v142", arabic: "عامل خطر", german: "Risikofaktor", article: "der", plural: "Risikofaktoren", example_de: "Ein Risikofaktor wird dokumentiert.", example_ar: "يتم توثيق عامل خطر.", level: "C1", category: "Arzt" },
  { id: "v143", arabic: "أمراض مصاحبة", german: "Komorbidität", article: "die", plural: "Komorbiditäten", example_de: "Die Komorbidität erschwert die Behandlung.", example_ar: "الأمراض المصاحبة تعقد العلاج.", level: "C1", category: "Arzt" },
  { id: "v144", arabic: "دليل علاجي", german: "Behandlungsleitlinie", article: "die", plural: "Behandlungsleitlinien", example_de: "Die Behandlungsleitlinie ist verbindlich.", example_ar: "الدليل العلاجي ملزم.", level: "C1", category: "Arzt" },
  { id: "v145", arabic: "تشخيص تفريقي", german: "Differenzialdiagnose", article: "die", plural: "Differenzialdiagnosen", example_de: "Die Differenzialdiagnose ist komplex.", example_ar: "التشخيص التفريقي معقد.", level: "C1", category: "Arzt" },
  { id: "v146", arabic: "هيكل الرعاية", german: "Versorgungsstruktur", article: "die", plural: "Versorgungsstrukturen", example_de: "Die Versorgungsstruktur wird verbessert.", example_ar: "هيكل الرعاية يتم تحسينه.", level: "C1", category: "Arzt" },
  { id: "v147", arabic: "سيرة مرضية", german: "Anamnese", article: "die", plural: "Anamnesen", example_de: "Die Anamnese ist ausführlich.", example_ar: "السيرة المرضية مفصلة.", level: "C1", category: "Arzt" },
  { id: "v148", arabic: "توقع", german: "Prognose", article: "die", plural: "Prognosen", example_de: "Die Prognose ist günstig.", example_ar: "التوقع جيد.", level: "C1", category: "Arzt" },
  { id: "v149", arabic: "تدخل علاجي", german: "Intervention", article: "die", plural: "Interventionen", example_de: "Die Intervention war notwendig.", example_ar: "التدخل العلاجي كان ضروريًا.", level: "C1", category: "Arzt" },
  { id: "v150", arabic: "وقاية", german: "Prävention", article: "die", plural: "-", example_de: "Prävention reduziert Risiken.", example_ar: "الوقاية تقلل المخاطر.", level: "C1", category: "Arzt" },
  { id: "v151", arabic: "جمعية الملاك", german: "Eigentümergemeinschaft", article: "die", plural: "Eigentümergemeinschaften", example_de: "Die Eigentümergemeinschaft entscheidet gemeinsam.", example_ar: "جمعية الملاك تقرر معًا.", level: "C1", category: "Wohnung" },
  { id: "v152", arabic: "احتياطي الإصلاحات", german: "Instandsetzungsrücklage", article: "die", plural: "Instandsetzungsrücklagen", example_de: "Die Instandsetzungsrücklage ist ausreichend.", example_ar: "احتياطي الإصلاحات كافٍ.", level: "C1", category: "Wohnung" },
  { id: "v153", arabic: "حق السكن", german: "Wohnrecht", article: "das", plural: "Wohnrechte", example_de: "Das Wohnrecht ist vertraglich geregelt.", example_ar: "حق السكن منظم تعاقديًا.", level: "C1", category: "Wohnung" },
  { id: "v154", arabic: "اعتماد الطاقة", german: "Energiezertifizierung", article: "die", plural: "Energiezertifizierungen", example_de: "Die Energiezertifizierung ist Pflicht.", example_ar: "اعتماد الطاقة إلزامي.", level: "C1", category: "Wohnung" },
  { id: "v155", arabic: "تجديد شامل", german: "Kernsanierung", article: "die", plural: "Kernsanierungen", example_de: "Die Kernsanierung erhöht den Wert.", example_ar: "التجديد الشامل يزيد القيمة.", level: "C1", category: "Wohnung" },
  { id: "v156", arabic: "ضوضاء", german: "Lärmbelastung", article: "die", plural: "Lärmbelastungen", example_de: "Die Lärmbelastung ist gering.", example_ar: "التلوث الضوضائي منخفض.", level: "C1", category: "Wohnung" },
  { id: "v157", arabic: "عقد صيانة", german: "Wartungsvertrag", article: "der", plural: "Wartungsverträge", example_de: "Der Wartungsvertrag gilt für zwei Jahre.", example_ar: "عقد الصيانة صالح لسنتين.", level: "C1", category: "Wohnung" },
  { id: "v158", arabic: "لوائح المنزل", german: "Hausordnung", article: "die", plural: "Hausordnungen", example_de: "Die Hausordnung regelt die Ruhezeiten.", example_ar: "لوائح المنزل تنظم أوقات الهدوء.", level: "C1", category: "Wohnung" },
  { id: "v159", arabic: "كفاءة الطاقة", german: "Energieeffizienz", article: "die", plural: "Energieeffizienzen", example_de: "Die Energieeffizienz ist ausgezeichnet.", example_ar: "كفاءة الطاقة ممتازة.", level: "C1", category: "Wohnung" },
  { id: "v160", arabic: "بنية المبنى", german: "Bausubstanz", article: "die", plural: "Bausubstanzen", example_de: "Die Bausubstanz ist stabil.", example_ar: "بنية المبنى مستقرة.", level: "C1", category: "Wohnung" }
];

const sentences = [
  { id: "s1", arabic: "على الرغم من ضغط العمل، أجد وقتًا للدراسة.", german: "Trotz des Arbeitsdrucks finde ich Zeit zum Lernen.", level: "B1", category: "Alltag" },
  { id: "s2", arabic: "أحاول تحسين لغتي من خلال قراءة المقالات.", german: "Ich versuche, meine Sprache durch das Lesen von Artikeln zu verbessern.", level: "B1", category: "Alltag" },
  { id: "s3", arabic: "إذا كان لدي وقت، أذهب للمشي في الحديقة.", german: "Wenn ich Zeit habe, gehe ich im Park spazieren.", level: "B1", category: "Alltag" },
  { id: "s4", arabic: "أحتاج إلى نصيحتك حول هذا القرار.", german: "Ich brauche deinen Rat zu dieser Entscheidung.", level: "B1", category: "Alltag" },
  { id: "s5", arabic: "في رأيي، التواصل الواضح يوفر الوقت.", german: "Meiner Meinung nach spart klare Kommunikation Zeit.", level: "B1", category: "Alltag" },
  { id: "s6", arabic: "أفضل تناول الطعام في المنزل لتجنب التكاليف.", german: "Ich esse lieber zu Hause, um Kosten zu sparen.", level: "B1", category: "Essen" },
  { id: "s7", arabic: "هل لديك أي حساسية يجب أن أخبر بها المطبخ؟", german: "Hast du Allergien, die ich der Küche mitteilen soll?", level: "B1", category: "Essen" },
  { id: "s8", arabic: "سأحجز طاولة لأن المطعم مزدحم مساءً.", german: "Ich reserviere einen Tisch, weil das Restaurant abends voll ist.", level: "B1", category: "Essen" },
  { id: "s9", arabic: "أحاول تقليل السكر في نظامي الغذائي.", german: "Ich versuche, Zucker in meiner Ernährung zu reduzieren.", level: "B1", category: "Essen" },
  { id: "s10", arabic: "الطاهي أوصى بوجبة اليوم الخاصة.", german: "Der Koch hat die Tagesspezialität empfohlen.", level: "B1", category: "Essen" },
  { id: "s11", arabic: "تمت ترقية زميلي لأنه أظهر مبادرة.", german: "Mein Kollege wurde befördert, weil er Initiative gezeigt hat.", level: "B1", category: "Arbeit" },
  { id: "s12", arabic: "نحتاج إلى تنسيق قبل إرسال التقرير.", german: "Wir brauchen eine Abstimmung, bevor wir den Bericht senden.", level: "B1", category: "Arbeit" },
  { id: "s13", arabic: "المدير طلب تحديد الأولويات لهذا الأسبوع.", german: "Der Chef hat verlangt, dass wir die Prioritäten für diese Woche festlegen.", level: "B1", category: "Arbeit" },
  { id: "s14", arabic: "سأشارك في دورة تدريبية لتطوير مهاراتي.", german: "Ich nehme an einer Fortbildung teil, um meine Fähigkeiten zu verbessern.", level: "B1", category: "Arbeit" },
  { id: "s15", arabic: "المفاوضات استغرقت وقتًا أطول من المتوقع.", german: "Die Verhandlungen haben länger gedauert als erwartet.", level: "B1", category: "Arbeit" },
  { id: "s16", arabic: "أشعر بتحسن لكن الأعراض لم تختف تمامًا.", german: "Ich fühle mich besser, aber die Symptome sind nicht ganz verschwunden.", level: "B1", category: "Arzt" },
  { id: "s17", arabic: "الطبيب طلب فحصًا إضافيًا للتأكد.", german: "Der Arzt hat eine zusätzliche Untersuchung verlangt, um sicherzugehen.", level: "B1", category: "Arzt" },
  { id: "s18", arabic: "أحتاج إلى وصفة طبية لشراء الدواء.", german: "Ich brauche eine Verschreibung, um das Medikament zu kaufen.", level: "B1", category: "Arzt" },
  { id: "s19", arabic: "سأقدم طلبًا للحصول على إجازة مرضية.", german: "Ich werde eine Krankschreibung beantragen.", level: "B1", category: "Arzt" },
  { id: "s20", arabic: "الفحص الطبي الدوري يساعد على الوقاية.", german: "Regelmäßige Check-ups helfen bei der Vorsorge.", level: "B1", category: "Arzt" },
  { id: "s21", arabic: "المساحة كافية لكنني أبحث عن حي أكثر هدوءًا.", german: "Die Wohnfläche reicht, aber ich suche eine ruhigere Nachbarschaft.", level: "B1", category: "Wohnung" },
  { id: "s22", arabic: "أود مناقشة بنود عقد الإيجار بالتفصيل.", german: "Ich möchte die Punkte des Mietvertrags im Detail besprechen.", level: "B1", category: "Wohnung" },
  { id: "s23", arabic: "إذا ظهرت مشكلة، سأبلغ صاحب الشقة فورًا.", german: "Wenn ein Problem auftaucht, informiere ich den Vermieter sofort.", level: "B1", category: "Wohnung" },
  { id: "s24", arabic: "خدمات إضافية هذا الشهر كانت مرتفعة.", german: "Die Nebenkosten waren diesen Monat hoch.", level: "B1", category: "Wohnung" },
  { id: "s25", arabic: "الإصلاحات ستتم خلال يومين حسب الاتفاق.", german: "Die Reparaturen werden laut Vereinbarung in zwei Tagen erledigt.", level: "B1", category: "Wohnung" },
  { id: "s26", arabic: "أحاول شرح وجهة نظري بهدوء لتجنب سوء الفهم.", german: "Ich versuche, meinen Standpunkt ruhig zu erklären, um Missverständnisse zu vermeiden.", level: "B1", category: "Alltag" },
  { id: "s27", arabic: "عندما أكون متعبًا، أفضل البقاء في المنزل.", german: "Wenn ich müde bin, bleibe ich lieber zu Hause.", level: "B1", category: "Alltag" },
  { id: "s28", arabic: "التخطيط الجيد يجعل العمل أسهل.", german: "Gute Planung macht die Arbeit leichter.", level: "B1", category: "Arbeit" },
  { id: "s29", arabic: "قرأت التقييمات قبل اختيار المطعم.", german: "Ich habe die Bewertungen gelesen, bevor ich das Restaurant gewählt habe.", level: "B1", category: "Essen" },
  { id: "s30", arabic: "أريد تحسين لغتي لأتواصل بثقة.", german: "Ich möchte meine Sprache verbessern, um selbstbewusst zu kommunizieren.", level: "B1", category: "Alltag" },
  { id: "s31", arabic: "أحاول تنظيم يومي بشكل أفضل.", german: "Ich versuche, meinen Alltag besser zu strukturieren.", level: "B2", category: "Alltag" },
  { id: "s32", arabic: "بعد موازنة الخيارات اخترت الدورة.", german: "Nach einer Abwägung habe ich mich für den Kurs entschieden.", level: "B2", category: "Alltag" },
  { id: "s33", arabic: "المزيد من الهدوء يساعدني في الأسابيع المجهدة.", german: "Mehr Gelassenheit hilft mir in stressigen Wochen.", level: "B2", category: "Alltag" },
  { id: "s34", arabic: "المنظور الجديد يحفزني على الاستمرار.", german: "Die neue Perspektive motiviert mich, weiterzulernen.", level: "B2", category: "Alltag" },
  { id: "s35", arabic: "الثبات مهم لتحقيق الأهداف.", german: "Konsequenz ist wichtig, um Ziele zu erreichen.", level: "B2", category: "Alltag" },
  { id: "s36", arabic: "العلاقة بين النوم والتعلم واضحة.", german: "Der Zusammenhang zwischen Schlaf und Lernen ist klar.", level: "B2", category: "Alltag" },
  { id: "s37", arabic: "طريقة التحضير تغير الطعم بشكل واضح.", german: "Die Zubereitungsart verändert den Geschmack deutlich.", level: "B2", category: "Essen" },
  { id: "s38", arabic: "المنتجات الموسمية غالبًا ما تكون طازجة وأرخص.", german: "Saisonprodukte sind oft frischer und günstiger.", level: "B2", category: "Essen" },
  { id: "s39", arabic: "ننتبه إلى حجم الحصة عند العشاء.", german: "Wir achten auf die Portionsgröße beim Abendessen.", level: "B2", category: "Essen" },
  { id: "s40", arabic: "قائمة المكونات مهمة بسبب الحساسية.", german: "Die Zutatenliste ist wichtig wegen Allergien.", level: "B2", category: "Essen" },
  { id: "s41", arabic: "استغلال البقايا يوفر الوقت والمال.", german: "Resteverwertung spart Zeit und Geld.", level: "B2", category: "Essen" },
  { id: "s42", arabic: "توازن السعرات يساعدني على البقاء نشيطًا.", german: "Eine ausgewogene Kalorienbalance hält mich fit.", level: "B2", category: "Essen" },
  { id: "s43", arabic: "تم تعريف مرحلة المشروع بوضوح في الفريق.", german: "Die Projektphase wurde im Team klar definiert.", level: "B2", category: "Arbeit" },
  { id: "s44", arabic: "الأهداف محددة لهذا الربع.", german: "Unsere Zielvorgaben sind für dieses Quartal festgelegt.", level: "B2", category: "Arbeit" },
  { id: "s45", arabic: "تحليل المخاطر يساعد على اكتشاف المشاكل مبكرًا.", german: "Eine Risikoanalyse hilft, Probleme früh zu erkennen.", level: "B2", category: "Arbeit" },
  { id: "s46", arabic: "تنسيق الفريق أصبح أفضل بفضل الأدوار الواضحة.", german: "Die Teamkoordination klappt besser durch klare Rollen.", level: "B2", category: "Arbeit" },
  { id: "s47", arabic: "تحسين العمليات يرفع الجودة.", german: "Die Prozessoptimierung steigert die Qualität.", level: "B2", category: "Arbeit" },
  { id: "s48", arabic: "تم الوصول إلى المرحلة المهمة في الوقت المحدد.", german: "Der Meilenstein wurde pünktlich erreicht.", level: "B2", category: "Arbeit" },
  { id: "s49", arabic: "بعد العملية تبدأ الرعاية اللاحقة فورًا.", german: "Nach der Operation beginnt die Nachsorge sofort.", level: "B2", category: "Arzt" },
  { id: "s50", arabic: "حصلت على رأي ثانٍ.", german: "Ich habe eine Zweitmeinung eingeholt.", level: "B2", category: "Arzt" },
  { id: "s51", arabic: "يتم تعديل خطة العلاج بشكل منتظم.", german: "Der Behandlungsplan wird regelmäßig angepasst.", level: "B2", category: "Arzt" },
  { id: "s52", arabic: "الآثار الجانبية حتى الآن خفيفة.", german: "Die Nebenwirkungen sind bisher mild.", level: "B2", category: "Arzt" },
  { id: "s53", arabic: "إعادة التأهيل تستغرق عدة أسابيع.", german: "Die Rehabilitation dauert mehrere Wochen.", level: "B2", category: "Arzt" },
  { id: "s54", arabic: "أحتاج إلى إحالة لزيارة طبيب مختص.", german: "Für den Facharzt brauche ich eine Überweisung.", level: "B2", category: "Arzt" },
  { id: "s55", arabic: "العزل يقلل تكاليف التدفئة بشكل ملحوظ.", german: "Die Dämmung reduziert die Heizkosten spürbar.", level: "B2", category: "Wohnung" },
  { id: "s56", arabic: "التهوية الجيدة تمنع العفن.", german: "Gute Belüftung verhindert Schimmel.", level: "B2", category: "Wohnung" },
  { id: "s57", arabic: "المخطط مفتوح وحديث.", german: "Der Grundriss wirkt offen und modern.", level: "B2", category: "Wohnung" },
  { id: "s58", arabic: "الشرفة العلوية توفر مساحة كبيرة.", german: "Die Dachterrasse bietet viel Platz.", level: "B2", category: "Wohnung" },
  { id: "s59", arabic: "نظام المنزل الذكي يوفر الطاقة.", german: "Ein Smart-Home-System spart Energie.", level: "B2", category: "Wohnung" },
  { id: "s60", arabic: "مؤشر الإيجارات يساعد في التفاوض على السعر.", german: "Der Mietspiegel hilft bei der Preisverhandlung.", level: "B2", category: "Wohnung" },
  { id: "s61", arabic: "تغير القيم يؤثر على قراراتنا.", german: "Der Wertewandel beeinflusst unsere Entscheidungen.", level: "C1", category: "Alltag" },
  { id: "s62", arabic: "وعي الاستدامة يحدد الكثير من اختياراتي.", german: "Nachhaltigkeitsbewusstsein prägt meinen Alltag.", level: "C1", category: "Alltag" },
  { id: "s63", arabic: "المرونة النفسية تساعد على تجاوز الانتكاسات.", german: "Resilienz hilft, mit Rückschlägen umzugehen.", level: "C1", category: "Alltag" },
  { id: "s64", arabic: "تمت صياغة السؤال بدقة.", german: "Die Fragestellung wurde präzise formuliert.", level: "C1", category: "Alltag" },
  { id: "s65", arabic: "التقنين يحمي المستهلك والبيئة.", german: "Regulierung schützt Verbraucher und Umwelt.", level: "C1", category: "Alltag" },
  { id: "s66", arabic: "تماسك الحجج يقنع بسرعة أكبر.", german: "Kohärenz in Argumenten überzeugt schneller.", level: "C1", category: "Alltag" },
  { id: "s67", arabic: "يتم توثيق مصدر المكونات بشكل شفاف.", german: "Die Zutatenherkunft wird transparent dokumentiert.", level: "C1", category: "Essen" },
  { id: "s68", arabic: "تعقيد النكهة علامة جودة مهمة.", german: "Geschmackskomplexität ist ein Qualitätsmerkmal.", level: "C1", category: "Essen" },
  { id: "s69", arabic: "التخمير يحسن النكهة ومدة الصلاحية.", german: "Fermentation verbessert Aroma und Haltbarkeit.", level: "C1", category: "Essen" },
  { id: "s70", arabic: "وسم المواد المسببة للحساسية إلزامي.", german: "Allergenkennzeichnung ist in der Küche Pflicht.", level: "C1", category: "Essen" },
  { id: "s71", arabic: "تمت مراجعة سلسلة الإنتاج بالكامل.", german: "Die Produktionskette wurde lückenlos geprüft.", level: "C1", category: "Essen" },
  { id: "s72", arabic: "فن الطهي يعكس الثقافة الإقليمية.", german: "Kulinarik spiegelt regionale Kultur wider.", level: "C1", category: "Essen" },
  { id: "s73", arabic: "تمت إعادة توجيه استراتيجية الشركة.", german: "Die Unternehmensstrategie wurde neu ausgerichtet.", level: "C1", category: "Arbeit" },
  { id: "s74", arabic: "أصحاب المصلحة يتوقعون أولويات واضحة.", german: "Stakeholder erwarten klare Prioritäten.", level: "C1", category: "Arbeit" },
  { id: "s75", arabic: "إدارة النزاعات تمنع التصعيد في الفريق.", german: "Konfliktmanagement verhindert Eskalationen im Team.", level: "C1", category: "Arbeit" },
  { id: "s76", arabic: "عملية التحول تستغرق عدة سنوات.", german: "Der Transformationsprozess dauert mehrere Jahre.", level: "C1", category: "Arbeit" },
  { id: "s77", arabic: "سيتم نشر تقرير الاستدامة قريبًا.", german: "Der Nachhaltigkeitsbericht wird veröffentlicht.", level: "C1", category: "Arbeit" },
  { id: "s78", arabic: "كفاءة القيادة تقوي التعاون.", german: "Führungskompetenz stärkt die Zusammenarbeit.", level: "C1", category: "Arbeit" },
  { id: "s79", arabic: "التشخيص التفريقي معقد ويحتاج وقتًا.", german: "Die Differenzialdiagnose ist komplex und zeitaufwendig.", level: "C1", category: "Arzt" },
  { id: "s80", arabic: "الأمراض المصاحبة تعقد العلاج بشكل واضح.", german: "Komorbidität erschwert die Behandlung deutlich.", level: "C1", category: "Arzt" },
  { id: "s81", arabic: "الالتزام بالعلاج يحدد النجاح.", german: "Therapieadhärenz entscheidet über den Erfolg.", level: "C1", category: "Arzt" },
  { id: "s82", arabic: "يتم الالتزام بدليل العلاج بدقة.", german: "Die Behandlungsleitlinie wird strikt beachtet.", level: "C1", category: "Arzt" },
  { id: "s83", arabic: "تم توثيق السيرة المرضية بالتفصيل.", german: "Die Anamnese wurde ausführlich dokumentiert.", level: "C1", category: "Arzt" },
  { id: "s84", arabic: "الوقاية تقلل المخاطر على المدى الطويل.", german: "Prävention senkt langfristig die Risiken.", level: "C1", category: "Arzt" },
  { id: "s85", arabic: "جمعية الملاك تصوت على الاحتياطي.", german: "Die Eigentümergemeinschaft stimmt über die Rücklage ab.", level: "C1", category: "Wohnung" },
  { id: "s86", arabic: "اعتماد الطاقة شرط للبيع.", german: "Die Energiezertifizierung ist Voraussetzung für den Verkauf.", level: "C1", category: "Wohnung" },
  { id: "s87", arabic: "التجديد الشامل يرفع قيمة العقار.", german: "Eine Kernsanierung erhöht den Immobilienwert.", level: "C1", category: "Wohnung" },
  { id: "s88", arabic: "تم قياس الضوضاء رسميًا.", german: "Die Lärmbelastung wurde offiziell gemessen.", level: "C1", category: "Wohnung" },
  { id: "s89", arabic: "عقد الصيانة يغطي جميع الأنظمة.", german: "Der Wartungsvertrag deckt alle Anlagen ab.", level: "C1", category: "Wohnung" },
  { id: "s90", arabic: "تم فحص بنية المبنى من خبراء.", german: "Die Bausubstanz wurde von Experten geprüft.", level: "C1", category: "Wohnung" }
];
